### ISSUE TITLE
[WIP] TODO

### ISSUE THREAD

**Issue by oti** [oti/tkgenv#1]
- shell script
  - [X] gitのuser.nameがアレしてしまう前にソレするやつ
  - [X] evenizer.sh
  - [ ] npm-preinstall.sh
    - [X] npm i -g evenizer
    - [X] npm i -g inlining
- gulp
  - [ ] gulp
  - [ ] run-sequence
  - [ ] browser-sync
  - [ ] gulp-autoprefixer
  - [ ] gulp-concat
  - [ ] gulp-load-plugins
  - [ ] gulp-plumber
  - [ ] gulp-replace
  - [ ] gulp-sass
  - [ ] gulp-sourcemaps
  - [ ] gulp-uglify
  - [ ] gulp.spritesmith
- Grunt
  - [ ] grunt-cli
  - [ ] my-ip
  - [ ] time-grunt
  - [ ] assemble
  - [ ] load-grunt-tasks
  - [ ] grunt-autoprefixer
  - [ ] grunt-browser-sync
  - [ ] grunt-contrib-clean
  - [ ] grunt-contrib-watch
  - [ ] grunt-contrib-concat
  - [ ] grunt-contrib-htmlmin
  - [ ] grunt-contrib-imagemin
  - [ ] grunt-csso
  - [ ] grunt-kss
  - [ ] grunt-newer
  - [ ] grunt-notify
  - [ ] grunt-open
  - [ ] grunt-contrib-sass
  - [ ] grunt-spritesmith
  - [ ] grunt-sftp-deploy
- npm run-script
